version: '3'
services:
  backend:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/liftee-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: frontend/
    volumes:
      - ./frontend:/liftee-frontend
    ports:
      - "5173:5173"
  db:
    image: postgres:14.9
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

